sudo: required
language: go
services:
- docker
env:
  global:
  - ORGANIZATION=$DOCKER_USERNAME
matrix:
  include:
  - env: IMAGE_NAME=sonarr
  - env: IMAGE_NAME=radarr
before_install:
- make
script:
- make image
after_success: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; make push;
notifications:
  email: false
  slack:
    secure: KX6g4RlQXIlGtHuX1yuuOU4q/3JCnLO+g/b3vCu77rd8jZ6MN4n2htytDAVkLs2aiE+rWjCU+PO2xFkymRurw9f6qnPCgO8n9wkd8NCqEMVuFkPS0/wQ2ypob6LyoVG5TjoaEKFgQegcqw9wPqBdTBiY8U55GmyOT8ZOCEbUmBP8gOAWTGEQS7d7aAaYfFdX1WVP/cVqqqOWgc20vejNb1goZ49r8dpxO3RpOLVrazl9qIQU4EZJVnfVJCFXB5sDq/pJEQ/zCZzwOQSOoMEKI3FEbepOiZPN4GnEUEKrvFPqFN8e7Il+1H2Pg0t3hWwaYB/cYRzGUr0L0AmYhMIg679GkktLDBOk3XkzRQNrs9/23tBT7rHLlACEVCpgUOVpwATmSFyeXTpKJApw/iwTaEM/e5PtFXZ04waH13xp74+E/YaQGFXh6NSsxuCTYZfO8WqszfHx60eckszkn7Jc8fOwDyyAEEBFU2fFenvSXR6DEL18Gf+4dkx3LQIeqxGBNzcF9YkZHQUQgjxNuNoQBfLFembJCFGheHgy4rSjCGlY1bTn1VDLoBOQYYcF86J5MNSVTk6fBf8UV02J92OPQe06MDRfmI4DNnw+VfhjxuWcUaUtMx/f57vVY1LQiH2EouX0zusYjxiVC8SPp/EoGEw9ErI3Kfkwf4evuRze8So=
